---
title: "Data Tidying"
author: "Monika Sikand"
date: "1/16/2019"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning = F, message = F}
library(dplyr)
library(tidyr)
#library(stats)
```
 to call a function from a specific package 'package_name::function_name(...)'
 
# Data Cleaning

Read in data file
```{r}
catch_df <- read.csv(url( "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1",method = "libcurl"), stringsAsFactors = FALSE)
head(catch_df)
```

control +SHift + m gives %>% pipe operator
or

command + shift + m gives %>% pipe operator

catch_cleaned <- catch_df %>% 
  select(-All, -notesRegCode)
  
  * Remove marginal some and notes column
  * Move from wide to long format

```{r}
catch_long <- catch_df %>% 
  select(-All, -notesRegCode)%>%  # negative values remove columns
  gather(key = "species", value = "catch",-Year, -Region)

head(catch_long)
```

%>% 

```{r}
catch_cleaned <- catch_long %>%
  rename(catch_thousands = catch)

head(catch_cleaned)
```

```{r}
catch_cleaned <- catch_long %>%
  rename(catch_thousands = catch)
  #mutate(catch = catch_thousands * 1000)
head(catch_cleaned)
```


```{r}
test_catch <- as.integer(catch_cleaned$catch_thousands)

i <- which(is.na(test_catch) == T)

catch_cleaned[i, ]
```
# Split- Apply-Combine

# Joins




